scrape_configs:
    - job_name: "nginx-website"
      scrape_interval: 15s
      metrics_path: "/metrics"
      static_configs:
          - targets: ["nginx-exporter:9113"]
            basic_auth:
                username: ${NGINX_USERNAME}
                password: ${NGINX_PASSWORD}
