scrape_configs:
    - job_name: "nginx-exporter"
      scrape_interval: 15s
      metrics_path: "/metrics"
      static_configs:
          - targets: ["nginx-exporter:9113"]

    - job_name: "logstash-exporter"
      scrape_interval: 5s
      metrics_path: "/metrics"
      static_configs:
          - targets: ["logstash-exporter:9198"]

    - job_name: "elasticsearch-exporter"
      scrape_interval: 5s
      metrics_path: "/metrics"
      static_configs:
          - targets: ["elasticsearch-exporter:9114"]

    - job_name: "kibana-exporter"
      scrape_interval: 5s
      metrics_path: "/metrics"
      static_configs:
          - targets: ["kibana-exporter:9684"]

    - job_name: "backend-exporter"
      scrape_interval: 5s
      metrics_path: "/metrics"
      static_configs:
          - targets: ["backend-exporter:9434"]
