volumes:
    grafana-data:
        driver: local
    prometheus-data:
        driver: local
    alertmanager-data:
        driver: local
    grafana-ssl:
        driver: local

networks:
    monitoring:
        driver: bridge

services:
    grafana:
        image: grafana/grafana:12.0.1
        container_name: grafana
        restart: always
        volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            - PROMETHEUS_HOST_URL=${PROMETHEUS_HOST_URL}
            - GF_SERVER_PROTOCOL=https
            - GF_SERVER_CERT_FILE=/etc/grafana/certs/grafana.crt
            - GF_SERVER_CERT_KEY=/etc/grafana/certs/grafana.key
        networks:
            - monitoring
        env_file:
            - .env
        user: "0"
        ports:
            - 3035:3000
        entrypoint: >
            sh -c "
            mkdir -p /etc/grafana/certs &&
            if [ ! -f /etc/grafana/certs/grafana.crt ]; then
            apk add --no-cache openssl && openssl req -x509 -nodes -days 365 \
            -newkey rsa:2048 \
            -keyout '/etc/grafana/certs/grafana.key' \
            -out '/etc/grafana/certs/grafana.crt' \
            -subj '/C=MA/ST=KH/L=KH/O=grafana/OU=IT/CN=grafana';
            fi &&
            chown -R 472:472 /etc/grafana/certs &&
            exec /run.sh
            "
        healthcheck:
            test: ["CMD-SHELL", "curl -k -f https://localhost:3000 || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 10

    prometheus:
        image: prom/prometheus:v3.4.0
        container_name: prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
            - prometheus-data:/prometheus
        networks:
            - monitoring
        ports:
            - 9090:9090
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=20d"
            - "--storage.tsdb.retention.size=10GB"

    alertmanager:
        image: prom/alertmanager:v0.28.0
        container_name: alertmanager
        restart: always
        volumes:
            - ./prometheus/alertmanager.yml:/config/alertmanager.yml
            - ./prometheus/mail.key:/etc/alertmanager/secrets/mail.key
            - alertmanager-data:/data
        command:
            - "--config.file=/config/alertmanager.yml"
            - "--log.level=debug"
        networks:
            - monitoring

include:
    - ./compose.exporters.yaml
